"""added user_id filed.

Revision ID: c35ebe5aa62a
Revises: a2fcddc2616f
Create Date: 2025-11-28 15:39:34.017959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35ebe5aa62a'
down_revision: Union[str, Sequence[str], None] = 'a2fcddc2616f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###
