"""added referral fields to users table

Revision ID: c69c04cea383
Revises: 99f6a08600d1
Create Date: 2026-01-04 16:30:01.749141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69c04cea383'
down_revision: Union[str, Sequence[str], None] = '99f6a08600d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referred_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('referral_code', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('referral_created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('admin', 'user', name='userrole'),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['referral_code'])
    op.create_foreign_key(None, 'users', 'users', ['referred_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'user', name='userrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'referral_created_at')
    op.drop_column('users', 'referral_code')
    op.drop_column('users', 'referred_by')
    # ### end Alembic commands ###
