"""added referral fields to users table

Revision ID: f0eb78b82f6a
Revises: c69c04cea383
Create Date: 2026-01-04 16:36:06.747801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0eb78b82f6a'
down_revision: Union[str, Sequence[str], None] = 'c69c04cea383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    op.execute("CREATE TYPE userrole AS ENUM ('admin', 'user')")
    
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False, server_default='user'))
    op.add_column('users', sa.Column('referred_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('referral_code', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('referral_created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['referral_code'])
    op.create_foreign_key(None, 'users', 'users', ['referred_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'referral_created_at')
    op.drop_column('users', 'referral_code')
    op.drop_column('users', 'referred_by')
    op.drop_column('users', 'role')
    
    # Drop enum type
    op.execute("DROP TYPE userrole")
    # ### end Alembic commands ###