"""client_secret default is now set to PENDING

Revision ID: 1d2325844d0b
Revises: c3f39a21bddf
Create Date: 2025-12-19 18:02:38.536574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2325844d0b'
down_revision: Union[str, Sequence[str], None] = 'c3f39a21bddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
