"""added referrer_id to payments table

Revision ID: 3f081d147414
Revises: 1d42fcb46809
Create Date: 2026-01-06 20:37:53.941494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f081d147414'
down_revision: Union[str, Sequence[str], None] = '1d42fcb46809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('referrer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'referrer_id')
    # ### end Alembic commands ###
