"""added checkout_session_id to payments

Revision ID: 5b7f3e10c089
Revises: 9bc3b501344d
Create Date: 2026-01-02 09:37:46.212707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7f3e10c089'
down_revision: Union[str, Sequence[str], None] = '9bc3b501344d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('checkout_session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'checkout_session_id')
    # ### end Alembic commands ###
