"""added checkout_url column to payments

Revision ID: bb5264ce9bac
Revises: 5b7f3e10c089
Create Date: 2026-01-02 12:00:02.591651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5264ce9bac'
down_revision: Union[str, Sequence[str], None] = '5b7f3e10c089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('checkout_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'checkout_url')
    # ### end Alembic commands ###
