"""added client_secret field to payments table

Revision ID: c3f39a21bddf
Revises: 6044eb4fd344
Create Date: 2025-12-19 17:26:00.128408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f39a21bddf'
down_revision: Union[str, Sequence[str], None] = '6044eb4fd344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('client_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'client_secret')
    # ### end Alembic commands ###
