"""removed referral_code from payments

Revision ID: ebee3dd04f66
Revises: 3f081d147414
Create Date: 2026-01-06 21:42:01.163282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebee3dd04f66'
down_revision: Union[str, Sequence[str], None] = '3f081d147414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'referral_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('referral_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
