"""added referral & comission tables

Revision ID: f27193a09e74
Revises: bb5264ce9bac
Create Date: 2026-01-04 07:51:52.902489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f27193a09e74'
down_revision: Union[str, Sequence[str], None] = 'bb5264ce9bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referrer_id', sa.String(), nullable=False),
    sa.Column('referred_id', sa.String(), nullable=False),
    sa.Column('referral_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('commissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referral_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('audit_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.add_column('payments', sa.Column('referral_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'referral_code')
    op.drop_table('commissions')
    op.drop_table('referrals')
    # ### end Alembic commands ###
