# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x06orders\"s\n\x19UpdateOrderPaymentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\npayment_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12 \n\x18stripe_payment_intent_id\x18\x04 \x01(\t\"W\n\x1aUpdateOrderPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x16\n\x0eupdated_status\x18\x03 \x01(\t2q\n\x0cOrderService\x12\x61\n\x18UpdateOrderPaymentStatus\x12!.orders.UpdateOrderPaymentRequest\x1a\".orders.UpdateOrderPaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEORDERPAYMENTREQUEST']._serialized_start=24
  _globals['_UPDATEORDERPAYMENTREQUEST']._serialized_end=139
  _globals['_UPDATEORDERPAYMENTRESPONSE']._serialized_start=141
  _globals['_UPDATEORDERPAYMENTRESPONSE']._serialized_end=228
  _globals['_ORDERSERVICE']._serialized_start=230
  _globals['_ORDERSERVICE']._serialized_end=343
# @@protoc_insertion_point(module_scope)
