# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payments.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payments.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epayments.proto\x12\x08payments\"\xea\x01\n\x14\x43reatePaymentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x1c\n\x14payment_method_token\x18\x05 \x01(\t\x12>\n\x08metadata\x18\x06 \x03(\x0b\x32,.payments.CreatePaymentRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\'\n\x11GetPaymentRequest\x12\x12\n\npayment_id\x18\x01 \x01(\t\"C\n\rRefundRequest\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x0e\n\x06reason\x18\x03 \x01(\t\"\xd1\x01\n\x0fPaymentResponse\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x0e\n\x06status\x18\x05 \x01(\t\x12 \n\x18stripe_payment_intent_id\x18\x06 \x01(\t\x12\x1c\n\x14payment_method_token\x18\x07 \x01(\t\x12\x10\n\x08\x63urrency\x18\x08 \x01(\t\x12\x15\n\rclient_secret\x18\t \x01(\t\"e\n\x0eRefundResponse\x12\x11\n\trefund_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x0e\n\x06reason\x18\x05 \x01(\t2\xe6\x01\n\x0ePaymentService\x12J\n\rCreatePayment\x12\x1e.payments.CreatePaymentRequest\x1a\x19.payments.PaymentResponse\x12\x44\n\nGetPayment\x12\x1b.payments.GetPaymentRequest\x1a\x19.payments.PaymentResponse\x12\x42\n\rProcessRefund\x12\x17.payments.RefundRequest\x1a\x18.payments.RefundResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payments_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPAYMENTREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_CREATEPAYMENTREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_CREATEPAYMENTREQUEST']._serialized_start=29
  _globals['_CREATEPAYMENTREQUEST']._serialized_end=263
  _globals['_CREATEPAYMENTREQUEST_METADATAENTRY']._serialized_start=216
  _globals['_CREATEPAYMENTREQUEST_METADATAENTRY']._serialized_end=263
  _globals['_GETPAYMENTREQUEST']._serialized_start=265
  _globals['_GETPAYMENTREQUEST']._serialized_end=304
  _globals['_REFUNDREQUEST']._serialized_start=306
  _globals['_REFUNDREQUEST']._serialized_end=373
  _globals['_PAYMENTRESPONSE']._serialized_start=376
  _globals['_PAYMENTRESPONSE']._serialized_end=585
  _globals['_REFUNDRESPONSE']._serialized_start=587
  _globals['_REFUNDRESPONSE']._serialized_end=688
  _globals['_PAYMENTSERVICE']._serialized_start=691
  _globals['_PAYMENTSERVICE']._serialized_end=921
# @@protoc_insertion_point(module_scope)
