# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: commissions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'commissions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ommissions.proto\x12\x0b\x63ommissions\"(\n\x11\x43ommissionRequest\x12\x13\n\x0breferrer_id\x18\x01 \x01(\t\"\xb3\x01\n\x10\x43ommissionReport\x12\x13\n\x0breferrer_id\x18\x01 \x01(\t\x12\x19\n\x11total_commissions\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_amount\x18\x03 \x01(\x01\x12\x16\n\x0epending_amount\x18\x04 \x01(\x01\x12\x13\n\x0bpaid_amount\x18\x05 \x01(\x01\x12,\n\x0b\x63ommissions\x18\x06 \x03(\x0b\x32\x17.commissions.Commission\"^\n\nCommission\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t2i\n\x11\x43ommissionService\x12T\n\x13GetCommissionReport\x12\x1e.commissions.CommissionRequest\x1a\x1d.commissions.CommissionReportb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commissions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMISSIONREQUEST']._serialized_start=34
  _globals['_COMMISSIONREQUEST']._serialized_end=74
  _globals['_COMMISSIONREPORT']._serialized_start=77
  _globals['_COMMISSIONREPORT']._serialized_end=256
  _globals['_COMMISSION']._serialized_start=258
  _globals['_COMMISSION']._serialized_end=352
  _globals['_COMMISSIONSERVICE']._serialized_start=354
  _globals['_COMMISSIONSERVICE']._serialized_end=459
# @@protoc_insertion_point(module_scope)
