"""added receipt_url to orders

Revision ID: 17179fb08757
Revises: 26389b1162cc
Create Date: 2025-12-19 22:26:57.957936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17179fb08757'
down_revision: Union[str, Sequence[str], None] = '26389b1162cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('receipt_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'receipt_url')
    # ### end Alembic commands ###
