"""added payment id to orders table

Revision ID: 3002a8eb7c69
Revises: c35ebe5aa62a
Create Date: 2025-12-16 12:40:20.771123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3002a8eb7c69'
down_revision: Union[str, Sequence[str], None] = 'c35ebe5aa62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_id', sa.String(), nullable=True))
    op.alter_column('orders', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('orders', 'payment_id')
    # ### end Alembic commands ###
