"""added checkout_url field to orders

Revision ID: 80a0802891b6
Revises: f4952b5c9018
Create Date: 2026-01-02 20:11:29.447182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a0802891b6'
down_revision: Union[str, Sequence[str], None] = 'f4952b5c9018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('checkout_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'checkout_url')
    # ### end Alembic commands ###
